"use client";

import { motion } from "framer-motion";
import { Users, Copy, Check, TrendingUp, ShieldCheck, Zap } from "lucide-react";
import { useState, useMemo } from "react";
import { useWallet } from "@solana/wallet-adapter-react";
import { toast } from "sonner";

function FadeIn({ children, delay = 0 }: { children: React.ReactNode, delay?: number }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay, ease: [0.16, 1, 0.3, 1] }}
    >
      {children}
    </motion.div>
  );
}

export default function ReferralPage() {
  const { publicKey } = useWallet();
  const [copied, setCopied] = useState(false);

  // Dynamic link generation
  const inviteLink = useMemo(() => {
    if (!publicKey) return "Connect Wallet to see link";
    const base = typeof window !== "undefined" ? window.location.origin : "https://soldoway.app";
    return `${base}/r/${publicKey.toString()}`;
  }, [publicKey]);

  const handleCopy = () => {
    if (!publicKey) {
      toast.error("Please connect your wallet first");
      return;
    }
    navigator.clipboard.writeText(inviteLink);
    setCopied(true);
    toast.success("Referral link copied!");
    setTimeout(() => setCopied(false), 2000);
  };

  const stats = [
    { label: "Total Referrals", value: "0", sub: "Partners joined", icon: Users },
    { label: "Total Earnings", value: "0.00 SOL", sub: "2% Kickback on-chain", icon: TrendingUp },
  ];

  return (
    <div className="max-w-[1400px] mx-auto px-6 md:px-10 py-12 space-y-16">
      
      {/* Header */}
      <section className="border-b border-slate-100 pb-10">
        <FadeIn>
          <h1 className="text-4xl font-bold tracking-tight text-slate-900">Referral Program</h1>
          <p className="text-slate-500 font-medium mt-2">Earn 2% of every yield generated by the businesses you invite.</p>
        </FadeIn>
      </section>

      {/* Hero Link Section */}
      <section>
        <FadeIn delay={0.1}>
          <div className="bg-black text-white rounded-[40px] p-10 md:p-12 shadow-2xl relative overflow-hidden flex flex-col md:flex-row items-center justify-between gap-12 group">
            <div className="absolute top-0 right-0 w-96 h-96 bg-white/5 rounded-full blur-[100px] -translate-y-1/2 translate-x-1/2 pointer-events-none group-hover:bg-white/10 transition-all duration-700"></div>
            
            <div className="flex-1 text-center md:text-left z-10 space-y-6">
              <div className="w-14 h-14 bg-white/10 flex items-center justify-center rounded-2xl border border-white/10 mx-auto md:mx-0">
                <Users className="w-7 h-7 text-white" />
              </div>
              <div className="space-y-4">
                <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-white leading-tight">Grow the network,<br />Own the protocol.</h2>
                <p className="text-white/60 max-w-sm text-sm md:text-base leading-relaxed font-medium">
                  Directly mapped on-chain. Your rewards are secured by the Soldoway smart contract.
                </p>
              </div>
            </div>
            
            <div className="w-full md:w-auto z-10">
              <div className="flex flex-col sm:flex-row items-center gap-3 bg-white/5 p-3 rounded-2xl border border-white/10 backdrop-blur-xl">
                <div className="flex items-center px-4 py-3 bg-white/[0.03] rounded-xl border border-white/[0.05] min-w-[280px]">
                  <span className="text-xs font-mono text-white/50 truncate max-w-[240px]">{inviteLink}</span>
                </div>
                <button 
                  onClick={handleCopy}
                  className="w-full sm:w-auto shrink-0 bg-white text-black hover:bg-slate-200 rounded-xl px-8 py-4 text-sm font-bold transition-all flex items-center justify-center gap-3 active:scale-95"
                >
                  {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                  {copied ? "Link Copied" : "Copy Link"}
                </button>
              </div>
            </div>
          </div>
        </FadeIn>
      </section>

      {/* Stats Breakdown */}
      <section className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {stats.map((stat, i) => (
          <FadeIn key={stat.label} delay={0.2 + (i * 0.1)}>
            <div className="bg-white border border-slate-200 rounded-[32px] p-10 shadow-sm hover:shadow-md transition-all group">
              <div className="flex justify-between items-start mb-6">
                <div className="p-4 bg-slate-50 rounded-2xl group-hover:bg-black group-hover:text-white transition-all text-slate-400">
                  <stat.icon className="w-6 h-6" />
                </div>
                <div className="flex items-center gap-1.5 text-[10px] font-black uppercase tracking-[0.15em] text-indigo-500 bg-indigo-50 px-3 py-1.5 rounded-full">
                  <Zap className="w-3.5 h-3.5 fill-indigo-500" />
                  Live Sync
                </div>
              </div>
              <div>
                <h3 className="text-4xl font-bold tracking-tight text-slate-900">{stat.value}</h3>
                <div className="flex items-center justify-between mt-3">
                  <p className="text-sm font-bold text-slate-400 uppercase tracking-widest">{stat.label}</p>
                  <p className="text-xs font-semibold text-slate-500 flex items-center gap-1.5">
                    <ShieldCheck className="w-3.5 h-3.5" /> {stat.sub}
                  </p>
                </div>
              </div>
            </div>
          </FadeIn>
        ))}
      </section>

    </div>
  );
}
