"use client";

import { motion } from "framer-motion";
import { Users, Copy, Check } from "lucide-react";
import { useState } from "react";

function FadeIn({ children, delay = 0 }: { children: React.ReactNode, delay?: number }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, delay }}
    >
      {children}
    </motion.div>
  );
}

export default function ReferralPage() {
  const [copied, setCopied] = useState(false);
  const inviteLink = "https://soldoway.app/invite/abc-123";

  const handleCopy = () => {
    navigator.clipboard.writeText(inviteLink);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-12 pb-20">
      <section>
        <FadeIn>
          <h1 className="text-2xl font-bold tracking-tight mb-6">Referral Program</h1>
        </FadeIn>
        <FadeIn delay={0.1}>
          <div className="bg-black text-white rounded-3xl p-8 md:p-10 shadow-lg relative overflow-hidden flex flex-col md:flex-row items-center justify-between gap-8">
            <div className="absolute top-0 right-0 w-64 h-64 bg-white/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2 pointer-events-none"></div>
            
            <div className="flex-1 text-center md:text-left z-10">
              <div className="w-12 h-12 bg-white/10 flex items-center justify-center rounded-xl mb-6 md:mb-5 border border-white/10 mx-auto md:mx-0">
                <Users className="w-6 h-6 text-white" />
              </div>
              <h2 className="text-2xl md:text-3xl font-bold tracking-tight mb-3 text-white">Invite & Earn</h2>
              <p className="text-white/70 max-w-sm text-sm md:text-base leading-relaxed">
                Share your unique link with businesses and earn a portion of the yield generated by their vaults.
              </p>
            </div>
            
            <div className="w-full md:w-auto z-10">
              <div className="flex flex-col sm:flex-row items-center gap-2 bg-white/10 p-2 rounded-2xl border border-white/10 backdrop-blur-md">
                <input 
                  type="text" 
                  readOnly 
                  title="Your invite link"
                  value={inviteLink}
                  className="bg-transparent border-none outline-none w-full md:w-64 px-4 py-2 text-sm font-mono text-white/90 focus:ring-0"
                />
                <button 
                  onClick={handleCopy}
                  className="w-full sm:w-auto shrink-0 bg-white text-black hover:bg-slate-200 rounded-xl px-6 py-3 text-sm font-semibold transition-all flex items-center justify-center gap-2"
                >
                  {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                  {copied ? "Copied" : "Copy"}
                </button>
              </div>
            </div>
          </div>
        </FadeIn>
      </section>
    </div>
  );
}
